/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernanceToken__factory } from "./GovernanceToken__factory";
export { SimpleDAO__factory } from "./SimpleDAO__factory";
